# golangci-lint configuration
# Compatible with golangci-lint v1.59.x

linters-settings:
  dupl:
    threshold: 100

  exhaustive:
    default-signifies-exhaustive: false

  funlen:
    lines: 100
    statements: 50

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/activadee/videocraft)

  goconst:
    min-len: 2
    min-occurrences: 2

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

  gocyclo:
    min-complexity: 15

  goimports:
    local-prefixes: github.com/activadee/videocraft

  mnd:
    settings:
      mnd:
        checks: argument,case,condition,return

  govet:
    enable:
      - shadow
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf

  lll:
    line-length: 140

  misspell:
    locale: US

  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - exportloopref
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - revive

issues:
  exclude-dirs:
    - generated_videos
    - temp
    - whisper_cache
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - funlen
        - goconst
        - gocyclo
        - errcheck
        - dupl
        - gosec
    - linters:
        - gocritic
      text: "unnecessaryDefer:"
    # Allow "cancelled" spelling (UK English)
    - linters:
        - misspell
      text: "`cancelled` is a misspelling of `canceled`"
    # Allow "dialogue" spelling (UK English)
    - linters:
        - misspell
      text: "`dialogue` is a misspelling of `dialog`"
    - linters:
        - misspell
      text: "`Dialogue` is a misspelling of `Dialog`"

run:
  timeout: 5m
