coverage:
  status:
    project:
      default:
        target: 75%
        threshold: 2%
    patch:
      default:
        target: 80%
        threshold: 2%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "**/*_test.go"
  - "**/testdata/**"
  - "**/mock/**"
  - "**/mocks/**"
  - "**/*.pb.go"
  - "generated_videos/**"
  - "temp/**"
  - "whisper_cache/**"